# Generated by Django 4.1 on 2022-09-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_experience_candidate_remove_profile_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
