# Generated by Django 4.1 on 2022-09-05 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='highest_degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='joining_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='passout_year',
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_degree', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=50)),
                ('joining_year', models.IntegerField()),
                ('passout_year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
