# Generated by Django 4.1 on 2022-09-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_college_remove_profile_highest_degree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='highest_degree',
            new_name='degree',
        ),
    ]
