# Generated by Django 4.1 on 2022-08-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_category_options_employer_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('vacancies', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], default='full time', max_length=30)),
                ('workmode', models.CharField(choices=[('on-site', 'on-site'), ('remote', 'remote'), ('hybrid', 'hybrid')], default='on-site', max_length=30)),
                ('experience_from', models.IntegerField()),
                ('experience_to', models.IntegerField()),
                ('job_description', models.TextField()),
                ('criteria', models.TextField()),
                ('payscale_from', models.IntegerField(blank=True, null=True)),
                ('payscale_to', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.job')),
            ],
        ),
    ]
