# Generated by Django 4.1 on 2022-08-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_job_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills',
            new_name='skill',
        ),
    ]
