# Generated by Django 4.1 on 2022-08-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='workmode',
            field=models.CharField(max_length=30),
        ),
    ]
