# Generated by Django 4.1 on 2022-09-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.employer'),
        ),
    ]
