# Generated by Django 4.1 on 2022-09-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skill', to='employer.job'),
        ),
    ]
