# Generated by Django 4.1 on 2022-09-16 07:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0013_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='Favourite',
        ),
    ]
