# Generated by Django 4.1 on 2022-09-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_favourite_applied_jobapplication_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='hired',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
