# Generated by Django 4.1 on 2022-09-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0016_job_applicants_job_hired_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
