# Generated by Django 4.1 on 2022-09-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0017_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=30, null=True),
        ),
    ]
