# Generated by Django 4.1 on 2022-09-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0018_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='workmode',
            field=models.CharField(default='On-site', max_length=30),
        ),
    ]
