# Generated by Django 4.1 on 2022-09-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0020_alter_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jd',
            field=models.FileField(blank=True, null=True, upload_to='jd'),
        ),
    ]
