# Generated by Django 4.1 on 2022-09-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0021_job_jd'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
