# Generated by Django 4.1 on 2022-09-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0023_location_remove_job_location_job_locn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='locn',
            new_name='location',
        ),
    ]
