# Generated by Django 4.1 on 2022-10-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0025_job_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_address',
            field=models.CharField(max_length=300),
        ),
    ]
