# Generated by Django 4.1 on 2022-10-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0026_alter_employer_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=30, null=True),
        ),
    ]
