# Generated by Django 4.1 on 2022-09-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='job',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
